spring:
  datasource:
    username: tutor
    password: password
    url: jdbc:postgresql://localhost:5432/tutor
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  rabbitmq:
    username: user
    password: password
    host: localhost
  data:
    redis:
      username: default
      password: systempass
logging:
  level:
    io.crstudio.tutor.auth: debug

jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaes

service:
  host: http://localhost:8080
  #  frontend path to request jwt from
  token-front: /request-signin
