spring:
  profiles:
    active: dev

jwt:
  secret: ${JWT_SECRET}

service:
  host: ${SERVICE_HOST}
  #  frontend path to request jwt from
  front-host: ${FRONT_HOST}
  token-front: ${FRONT_TOKEN_PATH}
  signup-front: ${FRONT_SIGNUP_PATH}
